# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96bcd4f7a4f7292837158f41d3e65c16d0f95000c2012f663bd9a33a04f825f05bf74a639f5dfaf1e03037df44a5a20c107747ef832a375fcff194bf47a58575

test:
  secret_key_base: 77f24cb560c8d8bfa5d1cc91aa68ae90e745314078439a7b95ea9c3021938f49e044ca5e9065631f8852becc77f2ea862a21f05d6cb7379903ea311dd9c569ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
